### ISSUE TITLE
Easier to debug faults

### ISSUE THREAD

**Issue by alexec** [kitproj/kit#30]
Apps tend to consist of:

* Downstream dependencies. E.g. Kafka. These don’t generally go faulty, because faults are caused by code changes.
* The app itself. This goes faulty a lot, because user changes the code and introduces faults.

When app goes faulty, we want to see the logs:

1. All logs, muxed to the terminal. 
2. Just the app logs.

Currently we do (2). Should we do (1)?

What I actually do is have a second terminal open running `tail -f`.  This is poor UX.

Should we switch out of max mode automatically?

**Comment by alexec** [comment]
One idea would be to show all logs by default. Each line would be prefixed by the task name and the task status.

**Comment by alexec** [comment]
After about 2h of experimentation the issue is still challenging. When your app is working just fine, you just want to see the fact it is fine. Yet once it is faulty, you want to see information that made it faulty.

**Comment by agilgur5** [comment]
A general option to change in between the two modes -- muxed together and single log stream -- at any point during a task run would be helpful IMO. I prefer to look at one at a time, so the muxing actually confuses me, especially without prefixes or separate colors (like [`ktail`](https://github.com/atombender/ktail) or [`kubetail`](https://github.com/johanhaleby/kubetail))

**Comment by alexec** [comment]
You can switch while running by pressing:

- 0+Enter - normal (muxed mode)
- 1+Enter - show error logs
- 2+Enter - show warning+ logs
- 3+Enter - show info+ logs
- 4+Enter - show all logs

**Comment by agilgur5** [comment]
Maybe I'm using the wrong terminology with "mux". I've seen the word ["interleaved" used](https://taskfile.dev/usage/#output-syntax) by some CLI tools which does describe what I meant.

As far as I understand, all the log level options still show logs from all concurrent tasks. Whereas seeing a single log stream from a single task is what I'm used to.

**Comment by alexec** [comment]
ok, which task?

**Comment by agilgur5** [comment]
It would be for any task that has dependencies. Being able to see an individual log stream instead of all of them together.

**Comment by alexec** [comment]
Logs are always saved in `logs/taskname.log`. Could you tail that?

**Comment by agilgur5** [comment]
Yes, I could. That's a workaround though, it would be great if something like that were built-in

**Comment by alexec** [comment]
This is now fixed.
