### ISSUE TITLE
Disable watch option

### ISSUE THREAD

**Issue by alexec** [kitproj/kit#40]
I’d like the option to disable watching for file changes. The use case is, I don’t want to restart services because I’m using hot reload which is much faster.

**Comment by agilgur5** [comment]
Disabling on a per task basis would be great, as some tasks have their own built-in, context-aware watching (such as hot reload), while others do not

**Comment by alexec** [comment]
This is available in v0.1.24

**Comment by agilgur5** [comment]
Hmm I realize now that Kit's `watch` field is slightly different [from Task](https://taskfile.dev/usage/#watch-tasks). `sources` are used both to decide whether to re-run a previously run task (in `make`-like fashion), as well as whether to restart it during watch mode. `watch: true` can additionally be configured per task to have a specific task run in watch mode, and `-w`/`--watch` to globally watch all running tasks.

Task seems more granular. Does Kit's `watch` field handle all 3 configurations in one? i.e. re-run previous task, restart running task, and watch a specific task. Or does Kit not have any checksum/timestamp-based caching of tasks at all? Wasn't really clear from the docs
