### ISSUE TITLE
Runs indefinitely when used as an `onCreateCommand` in GH Codespaces

### ISSUE THREAD

**Issue by agilgur5** [kitproj/kit#44]
Follow-up to https://github.com/argoproj/argo-workflows/pull/11928#issuecomment-1754165093 and https://github.com/argoproj/argo-workflows/issues/11423.

> [...] Codespaces running indefinitely on `kit pre-up`: https://github.com/argoproj/argo-workflows/issues/11423. I even got a notification from GH that it used up 24 hours of compute before I even had access to a terminal (it apparently ran all night even after I closed the tab and turned off my computer).
I just looked into that yesterday and think it can be solved by switching the `devcontainer`'s `onCreateCommand` to a `postCreateCommand`, but something weird is going on with how Codespaces is interacting with `kit` specifically at build-time. I saw it restart a few processes repeatedly too, not sure why.

Possibly related to #42 given the restarts I saw, but not sure

**Comment by agilgur5** [comment]
Can confirm that moving to a `postCreateCommand` fixed it (see https://github.com/argoproj/argo-workflows/pull/11981), though I'm not sure why `kit` runs indefinitely when used as an `onCreateCommand`

**Comment by alexec** [comment]
Seems fixed.
